<?xml version="1.0"?>
<!-- Interactable VDL_6_20_110 Ball Valve -->
<robot name="VDL_6_20_110_ball_valve" xmlns:xacro="http://www.ros.org/wiki/xacro">

    <!-- Dimensions for Inertias -->
    <!-- Base -->
    <xacro:property name="width1" value="0.5"/>
    <xacro:property name="height1" value="0.1"/>
    <xacro:property name="mass1" value="0.5"/>

    <!-- Handle -->
    <xacro:property name="length2" value="0.01"/>
    <xacro:property name="radius2" value="0.03"/>
    <xacro:property name="mass2" value="0.05"/>


    <!-- Import all Gazebo-customization elements -->
    <xacro:include filename="$(find manipulation_playground_articulated_devices)/devices/VDL_6_20_110_ball_valve/model/VDL_6_20_110_ball_valve.gazebo" />
    
    
    <!-- Used to fix switch to world -->
    <link name="world"/>

    <joint name="ball_valve_base_to_world" type="fixed">
        <parent link="world"/>
        <child link="base"/>
        <origin xyz="0 0 0" rpy="0 0 0"/>
    </joint>


    <!-- Ball Valve Base -->
    <link name="base">
        <collision>
            <origin xyz="0 0 0" rpy="0 -1.5708 0"/>
            <geometry>
                <cylinder radius="0.11" length="0.32"/>
            </geometry>
        </collision>

        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <mesh filename="package://manipulation_playground_articulated_devices/devices/VDL_6_20_110_ball_valve/model/VDL_6_20_110_ball_valve_base.dae"/>
            </geometry>
        </visual>

        <inertial>
            <origin xyz="0 0 ${height1/2}" rpy="0 0 0"/>
            <mass value="${mass1}"/>
            <inertia
                ixx="${mass1 / 12.0 * (width1*width1 + height1*height1)}" ixy="0.0" ixz="0.0"
                iyy="${mass1 / 12.0 * (height1*height1 + width1*width1)}" iyz="0.0"
                izz="${mass1 / 12.0 * (width1*width1 + width1*width1)}"/>
        </inertial>
    </link>

    <joint name="ball_valve_handle_to_base" type="fixed">
        <parent link="base"/>
        <child link="handle"/>
        <origin xyz="0 0 0.145" rpy="0 0 0"/>
    </joint>

    <link name="handle"/>

    <!-- Ball Valve Joint -->
    <joint name="ball_valve_joint" type="revolute">
        <parent link="handle"/>
        <child link="handle_rotated"/>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <axis xyz="0 0 1"/>
        <dynamics damping="0.0" friction="10.0" />
        <limit effort="100" velocity="0.5" lower="0" upper="1.5708" />
    </joint>

    <transmission name="ball_valve_trans">
        <type>transmission_interface/SimpleTransmission</type>
        <joint name="ball_valve_joint">
            <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
        </joint>
        <actuator name="ball_valve_actuator">
            <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
            <mechanicalReduction>1</mechanicalReduction>
        </actuator>
    </transmission>


    <!-- Ball Valve Handle -->
    <link name="handle_rotated">
        <collision>
            <origin xyz="0 0 -0.145" rpy="0 0 0"/>
            <geometry>
                <mesh filename="package://manipulation_playground_articulated_devices/devices/VDL_6_20_110_ball_valve/model/VDL_6_20_110_ball_valve_handle.dae"/>
            </geometry>
        </collision>

        <visual>
            <origin xyz="0 0 -0.145" rpy="0 0 0"/>
            <geometry>
                <mesh filename="package://manipulation_playground_articulated_devices/devices/VDL_6_20_110_ball_valve/model/VDL_6_20_110_ball_valve_handle.dae"/>
            </geometry>
        </visual>

        <inertial>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <mass value="${mass2}"/>
            <inertia
                ixx="${mass2 / 12.0 * (3.0*radius2*radius2 + length2*length2)}" ixy="0.0" ixz="0.0"
                iyy="${mass2 / 2.0 * (radius2*radius2)}" iyz="0.0"
                izz="${mass2 / 12.0 * (3.0*radius2*radius2 + length2*length2)}"/>
        </inertial>
    </link>


</robot>