<?xml version="1.0"?>
<!-- Interactable Hand Wheel -->
<robot name="hand_wheel" xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:arg name="continuous" default="true"/>
    <xacro:arg name="lower_limit" default="-3.1415"/>
    <xacro:arg name="upper_limit" default="3.1415"/>

    <xacro:macro name="hand_wheel" params="continuous:=true lower_limit:=-3.1415 upper_limit:=3.1415">

        <!-- Constants for Valve Dimensions -->
        <!-- Base -->
        <xacro:property name="width" value="0.1"/>
        <xacro:property name="height1" value="0.02"/>
        <xacro:property name="mass1" value="1"/>

        <!-- Neck -->
        <xacro:property name="length2" value="0.04"/>
        <xacro:property name="radius2" value="0.02"/>
        <xacro:property name="mass2" value="0.5"/>

        <!-- Ring -->
        <xacro:property name="length3" value="0.035"/>
        <xacro:property name="radius3" value="0.149"/>
        <xacro:property name="mass3" value="1"/>

        <!-- Grip -->
        <xacro:property name="length4" value="0.093"/>
        <xacro:property name="radius4" value="0.014"/>
        <xacro:property name="mass4" value="0.1"/>
        <xacro:property name="grip_offset_from_edge" value="0.016"/>


        <!-- Import all Gazebo-customization elements, including Gazebo colors -->
        <xacro:include filename="$(find manipulation_playground_articulated_devices)/devices/hand_wheel/model/hand_wheel.gazebo" />
        <!-- Import Rviz colors -->
        <xacro:include filename="$(find manipulation_playground_articulated_devices)/devices/hand_wheel/model/materials.xacro" />


        <!-- Used to fix device to world -->
        <link name="world"/>

        <joint name="hand_wheel_base_to_world" type="fixed">
            <parent link="world"/>
            <child link="base"/>
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </joint>


        <!-- Valve Base -->
        <link name="base">
            <collision>
                <origin xyz="0 0 ${height1/2}" rpy="0 0 0"/>
                <geometry>
                    <box size="${width} ${width} ${height1}"/>
                </geometry>
            </collision>

            <visual>
                <origin xyz="0 0 ${height1/2}" rpy="0 0 0"/>
                <geometry>
                    <box size="${width} ${width} ${height1}"/>
                </geometry>
                <material name="grey"/>
            </visual>

            <inertial>
                <origin xyz="0 0 ${height1/2}" rpy="0 0 0"/>
                <mass value="${mass1}"/>
                <inertia
                    ixx="${mass1 / 12.0 * (width*width + height1*height1)}" ixy="0.0" ixz="0.0"
                    iyy="${mass1 / 12.0 * (height1*height1 + width*width)}" iyz="0.0"
                    izz="${mass1 / 12.0 * (width*width + width*width)}"/>
            </inertial>
        </link>

        <joint name="hand_wheel_handle_to_base" type="fixed">
            <parent link="base"/>
            <child link="handle_zero"/>
            <origin xyz="0 0 ${height1}" rpy="0 0 0"/>
        </joint>

        <link name="handle_zero">
            <inertial>
                <origin xyz="0 0 0" rpy="0 0 0" />
                <mass value="1" />
                <inertia
                ixx="1.0" ixy="0.0" ixz="0.0"
                iyy="1.0" iyz="0.0"
                izz="1.0" />
            </inertial>
        </link>

        <!-- Valve Joint -->
        <xacro:if value="${continuous}">
            <joint name="hand_wheel_joint" type="continuous">
                <parent link="handle_zero"/>
                <child link="handle"/>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <axis xyz="0 0 1"/>
                <dynamics damping="0.0" friction="0.01" />
                <limit effort="100" velocity="0.5" />
            </joint>
        </xacro:if>

        <xacro:unless value="${continuous}">
            <joint name="hand_wheel_joint" type="revolute">
                <parent link="handle_zero"/>
                <child link="handle"/>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <axis xyz="0 0 1"/>
                <dynamics damping="0.0" friction="0.01" />
                <limit effort="100" lower="${lower_limit}" upper="${upper_limit}" velocity="0.5" />
            </joint>
        </xacro:unless>

        <transmission name="hand_wheel_trans">
            <type>transmission_interface/SimpleTransmission</type>
            <joint name="hand_wheel_joint">
                <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
            </joint>
            <actuator name="hand_wheel_actuator">
                <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
                <mechanicalReduction>1</mechanicalReduction>
            </actuator>
        </transmission>


        <!-- Valve Handle Neck -->
        <link name="handle">
            <collision>
                <origin xyz="0 0 ${length2/2}" rpy="0 0 0"/>
                <geometry>
                    <cylinder radius="${radius2}" length="${length2}"/>
                </geometry>
            </collision>

            <visual>
                <origin xyz="0 0 ${length2/2}" rpy="0 0 0"/>
                <geometry>
                    <cylinder radius="${radius2}" length="${length2}"/>
                </geometry>
                <material name="grey"/>
            </visual>

            <inertial>
                <origin xyz="0 0 ${length2/2}" rpy="0 0 0"/>
                <mass value="${mass2}"/>
                <inertia
                    ixx="${mass2 / 12.0 * (3.0*radius2*radius2 + length2*length2)}" ixy="0.0" ixz="0.0"
                    iyy="${mass2 / 12.0 * (3.0*radius2*radius2 + length2*length2)}" iyz="0.0"
                    izz="${mass2 / 2.0 * (radius2*radius2)}"/>
            </inertial>
        </link>

        <joint name="handle_neck_to_ring" type="fixed">
            <parent link="handle"/>
            <child link="ring"/>
            <origin xyz="0 0 ${length2}" rpy="0 0 0"/>
        </joint>


        <!-- Valve Handle Ring -->
        <link name="ring">
            <collision>
                <origin xyz="0 0 ${length3/2}" rpy="0 0 0"/>
                <geometry>
                    <cylinder radius="${radius3}" length="${length3}"/>
                </geometry>
            </collision>

            <visual>
                <origin xyz="0 0 ${length3/2}" rpy="0 0 0"/>
                <geometry>
                    <cylinder radius="${radius3}" length="${length3}"/>
                </geometry>
                <material name="dark_grey"/>
            </visual>

            <inertial>
                <origin xyz="0 0 ${length3/2}" rpy="0 0 0"/>
                <mass value="${mass3}"/>
                <inertia
                    ixx="${mass3 / 12.0 * (3.0*radius3*radius3 + length3*length3)}" ixy="0.0" ixz="0.0"
                    iyy="${mass3 / 12.0 * (3.0*radius3*radius3 + length3*length3)}" iyz="0.0"
                    izz="${mass3 / 2.0 * (radius3*radius3)}"/>
            </inertial>
        </link>


        <!-- Valve Handle Grip Joint -->
        <joint name="hand_wheel_ring_to_grip" type="fixed">
            <parent link="ring"/>
            <child link="grip"/>
            <origin xyz="0 ${radius3-radius4-grip_offset_from_edge} ${length3}" rpy="0 0 0"/>
            <!-- <axis xyz="0 0 1"/>
            <dynamics damping="1.0" friction="0.0" />
            <limit effort="100" velocity="10" /> -->
        </joint>


        <!-- Valve Handle Grip -->
        <link name="grip">
            <collision>
                <origin xyz="0 0 ${length4/2}" rpy="0 0 0"/>
                <geometry>
                    <cylinder radius="${radius4}" length="${length4}"/>
                </geometry>
            </collision>

            <visual>
                <origin xyz="0 0 ${length4/2}" rpy="0 0 0"/>
                <geometry>
                    <cylinder radius="${radius4}" length="${length4}"/>
                </geometry>
                <material name="dark_grey"/>
            </visual>

            <inertial>
                <origin xyz="0 0 ${length4/2}" rpy="0 0 0"/>
                <mass value="${mass4}"/>
                <inertia
                    ixx="${mass4 / 12.0 * (3.0*radius4*radius4 + length4*length4)}" ixy="0.0" ixz="0.0"
                    iyy="${mass4 / 12.0 * (3.0*radius4*radius4 + length4*length4)}" iyz="0.0"
                    izz="${mass4 / 2.0 * (radius4*radius4)}"/>
            </inertial>
        </link>
    </xacro:macro>

    <xacro:hand_wheel continuous="$(arg continuous)" lower_limit="$(arg lower_limit)" upper_limit="$(arg upper_limit)"/>
</robot>